{application,phoenix_ecto,
             [{registered,[]},
              {description,"Integration between Phoenix & Ecto"},
              {vsn,"2.0.2"},
              {modules,['Elixir.Phoenix.Ecto',
                        'Elixir.Phoenix.HTML.FormData.Ecto.Changeset',
                        'Elixir.Phoenix.HTML.Safe.Decimal',
                        'Elixir.Phoenix.HTML.Safe.Ecto.Date',
                        'Elixir.Phoenix.HTML.Safe.Ecto.DateTime',
                        'Elixir.Phoenix.HTML.Safe.Ecto.Time',
                        'Elixir.Plug.Exception.Ecto.CastError',
                        'Elixir.Plug.Exception.Ecto.NoResultsError',
                        'Elixir.Poison.Encoder.Ecto.Association.NotLoaded']},
              {applications,[kernel,stdlib,elixir,logger,ecto]}]}.